// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acxorfhgeukboaajxprr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjeG9yZmhnZXVrYm9hYWp4cHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTIwOTUsImV4cCI6MjA2MzIyODA5NX0.ZWMh8lIX15laijsO3lgQj9ImuRG4JcZfwSROaWs_orE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);